export const listOfRoutes = [
  { label: "/employee", id: "/employee" },
  {
    label: "/transaction/followupexport",
    id: "/transaction/followupexport"
  },
  { label: "/systemsettings/pln", id: "/systemsettings/pln" },
  {
    label: "/usersettings/nps-ranking-views",
    id: "/usersettings/nps-ranking-views"
  },
  { label: "/rating/widget", id: "/rating/widget" },
  { label: "/tablet/status", id: "/tablet/status" },
  { label: "/reporttable/npsclasses", id: "/reporttable/npsclasses" },
  { label: "/usersettings/signatures", id: "/usersettings/signatures" },
  {
    label: "/usersettings/extract-views",
    id: "/usersettings/extract-views"
  },
  { label: "/transaction/statistics", id: "/transaction/statistics" },
  { label: "/transaction/items", id: "/transaction/items" },
  { label: "/transaction/count", id: "/transaction/count" },
  { label: "/storegrouprelation", id: "/storegrouprelation" },
  { label: "/storegroup-hierarchy/load", id: "/storegroup-hierarchy/load" },
  { label: "/storegroup/import", id: "/storegroup/import" },
  { label: "/storegroup", id: "/storegroup" },
  { label: "/store/import", id: "/store/import" },
  { label: "/store", id: "/store" },
  { label: "/reward", id: "/reward" },
  { label: "/reporttable/npssummary", id: "/reporttable/npssummary" },
  { label: "/reporttable/npsranking", id: "/reporttable/npsranking" },
  { label: "/reporttable/engagement", id: "/reporttable/engagement" },
  { label: "/rating/item", id: "/rating/item" },
  { label: "/rating/history", id: "/rating/history" },
  { label: "/rating/classes", id: "/rating/classes" },
  { label: "/login/saml", id: "/login/saml" },
  { label: "/journeys", id: "/journeys" },
  { label: "/innerloop/customstatus", id: "/innerloop/customstatus" },
  { label: "/innerloop/settings", id: "/innerloop/settings" },
  { label: "/hierarchylevels", id: "/hierarchylevels" },
  { label: "/graph/ranking", id: "/graph/ranking" },
  { label: "/graph/pnd", id: "/graph/pnd" },
  { label: "/graph/nps", id: "/graph/nps" },
  { label: "/graph/item", id: "/graph/item" },
  { label: "/graph/engagement", id: "/graph/engagement" },
  { label: "/dashboard/parameter-type", id: "/dashboard/parameter-type" },
  { label: "/employee/extract", id: "/employee/extract" },
  { label: "/dashboard/widget-type", id: "/dashboard/widget-type" },
  { label: "/credentials/linkedAccount", id: "/credentials/linkedAccount" },
  { label: "/classes/journeys", id: "/classes/journeys" },
  { label: "/auto-classifications", id: "/auto-classifications" },
  { label: "/attempts", id: "/attempts" },
  { label: "/api/contacts", id: "/api/contacts" },
  { label: "/api/v1", id: "/api/v1" },
  { label: "/rating/form", id: "/rating/form" }
];
